# /backend/render.yaml
services:
  - type: web
    name: fordis-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "poetry install"
    startCommand: "poetry run uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: ENV
        value: production
