"""create password_reset_tokens table

Revision ID: 6f28cb8d274e
Revises: a1e3e950dc21
Create Date: 2025-03-25 23:45:52.235089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f28cb8d274e'
down_revision: Union[str, None] = 'a1e3e950dc21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key for the reset token entry'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User the reset token is associated with'),
    sa.Column('token', sa.String(length=128), nullable=False, comment='Secure random token'),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False, comment='Token expiration timestamp'),
    sa.Column('used', sa.Boolean(), nullable=False, comment='Whether this token has been used already'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
