"""initial schema rebuild

Revision ID: d4827f6d9a0e
Revises: 
Create Date: 2025-03-25 19:32:26.812371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4827f6d9a0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key (UUID)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address"),
    sa.Column('password_hash', sa.String(), nullable=False, comment='BCrypt-hashed password'),
    sa.Column('role', sa.Enum('free', 'client', 'manager', 'enterprise', name='userrole', native_enum=False), nullable=False, comment='Role of the user'),
    sa.Column('status', sa.Enum('active', 'grace', 'downgraded', 'banned', 'deactivated', name='userstatus', native_enum=False), nullable=False, comment='Account status used for login gating'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False, comment='Timestamp of user registration'),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True, comment='Last login timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
